I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1373, in script
    K "I've got nothing to do right now."
NameError: name 'name_input' is not defined. Did you mean: 'raw_input'?

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 1373, in script
    K "I've got nothing to do right now."
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 991, in execute
    renpy.exports.say(who, what, *args, **kwargs)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/exports/sayexports.py", line 129, in say
    who(what, *args, **kwargs)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/character.py", line 1526, in __call__
    who = self.prefix_suffix("who", self.who_prefix, who, self.who_suffix)
          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/character.py", line 1444, in prefix_suffix
    return sub(prefix) + sub(body) + sub(suffix)
                         ~~~^^^^^^              
  File "renpy/character.py", line 1421, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
  File "renpy/substitutions.py", line 355, in substitute
    s = interpolate(s, variables)  # type: ignore
        ~~~~~~~~~~~^^^^^^^^^^^^^^                
  File "renpy/substitutions.py", line 89, in interpolate
    raise e
  File "renpy/substitutions.py", line 81, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'name_input' is not defined. Did you mean: 'raw_input'?

Windows-11-10.0.26100-SP0 AMD64
Ren'Py 8.4.0.25071206
VEIL: Beneath The Surface 1.0
Mon Aug  4 11:41:39 2025
